#
# Makefile for pilot-core mavlink protocol library
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2024 Phoenix Systems
#

# Sensorhub client library
NAME := libmavlink
LOCAL_SRCS := mavlink.c
LOCAL_HEADERS := mavlink.h mavlink_enums.h
include $(static-lib.mk)
