#
# Makefile for kalman filter development application for Phoenix Pilot
#
# This source code and Makefile is designed for compilation from _user directory of phoenix - rtos - project
#
# Copyright 2022 Phoenix Systems
#

# Purpose of this development application is deep access into EKF far beyond normal user interface.
# This is the reason for directly using kalman_implem and kalman_core headers.

# EKF testing app
NAME := dev-ekf
LOCAL_SRCS := main.c
DEP_LIBS := libekf

include $(binary.mk)
