#
# Makefile for pilot-core utilities
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

NAME := libplog
LOCAL_SRCS := plog.c
LOCAL_HEADERS := plog.h

include $(static-lib.mk)
