#
# Makefile for algebra library tests
#
# Copyright 2023 Phoenix Systems
#
# %LICENSE%
#

NAME := ekflog_tests
LOCAL_SRCS := main.c tests.c ../reader.c ../writer.c

LIBS := unity

LOCAL_CFLAGS := -g
LOCAL_LDFLAGS := -g

include $(binary.mk)
