#
# Makefile for calibration application
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

NAME := libcalib
CALIBS := magmot.c magiron.c
LOCAL_SRCS := hmap.c common.c $(CALIBS)
DEPS := libalgeb libsensc libmctl
include $(static-lib.mk)
