#
# Makefile for calibration application
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

# Magnetometer calibration tool
NAME := calibtool
LOCAL_SRCS := main.c
DEP_LIBS := libcalib libmctl libalgeb libhmap
include $(binary.mk)
