#
# Makefile for pilot-core utilities
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

NAME := libparser
LOCAL_SRCS := parser.c
LOCAL_HEADERS := parser.h
DEP := libhmap

include $(static-lib.mk)
