#
# Makefile for pilot-core utilities
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

# Sensorhub client library
NAME := libsensc
LOCAL_SRCS := sensc.c corr.c
LOCAL_HEADERS := sensc.h
DEPS := libalgeb libcalib
include $(static-lib.mk)
