#
# Makefile for ekf algebra libraries:
# 
# libvec3d: quaternion + 3d vector library
# libmatrix: matrix calculations library  
#
# Copyright 2022 Phoenix Systems
#
# %LICENSE%
#

NAME := libvec3d
LOCAL_HEADERS = vec.h
LOCAL_SRCS = vec.c
include $(static-lib.mk)

NAME := libmatrix
LOCAL_SRCS := matrix.c
LOCAL_HEADERS := matrix.h
include $(static-lib.mk)