#
# Makefile for pilot-core utilities
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2023 Phoenix Systems
#

# Hash map library
NAME := liblogreader
LOCAL_SRCS := log_reader.c
LOCAL_HEADERS := log_reader.h
include $(static-lib.mk)
