#
# Makefile for pilot-core motor control utility
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

# Sensorhub client library
NAME := libmctl
LOCAL_SRCS := mctl.c
LOCAL_HEADERS := mctl.h
include $(static-lib.mk)
