#
# Makefile for Phoenix-PILOT plane control
#
# Copyright 2022 Phoenix Systems
#

NAME := plane-control
LOCAL_SRCS := control.c mma.c
DEP_LIBS := libekf libparser libhmap libalgeb libsensc libmctl libcalib libplog
LIBS := libzynq7000pwm
include $(binary.mk)
