#
# Makefile for pilot-core utilities
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

# Hash map library
NAME := hmap
LOCAL_SRCS := hmap.c
LOCAL_HEADERS := hmap.h
include $(static-lib.mk)
