#
# Makefile for Phoenix-PILOT quadcopter control
#
# Copyright 2022 Phoenix Systems
#

NAME := quad-control
LOCAL_SRCS := control.c pid.c mma.c
DEP_LIBS := libekf libmatrix libquat libvec3d
include $(binary.mk)
