#
# Makefile for pilot-core utilities
#
# This source code and Makefile is designed for compilation from phoenix-pilot-core
#
# Copyright 2022 Phoenix Systems
#

# Sensorhub client library
NAME := libcalib
LOCAL_SRCS := calib.c
LOCAL_HEADERS := calib.h
include $(static-lib.mk)
